services:
  - type: web
    name: telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python botauto.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: TOKEN
        value: 8753803503:AAFrgbdiJqWVzizGHfCtHME--sNMNJLgFs8